# Main Menu

MAIN_MENU_LOGIN = "1"
MAIN_MENU_TOUNOI = "2"
MAIN_MENU_REPORTS = "3"
MAIN_MENU_QUIT = "0"

# User Menu commun

LIST_CUSTOMERS = "1"
LIST_DEALS = "2"
LIST_EVENTS = "3"
LOG_OUT = "0"

# User Menu Manager

LIST_MANAGER_ASSIGN_EVENT = "4"
LIST_MANAGER_MANAGE_USER = "5"
LIST_MANAGER_MANAGE_CONTRACT = "6"

# User Menu Sales

LIST_SALES_CREATE_NEW_CUSTOMER = "4"
LIST_SALES_UPDATE_CUSTOMER = "5"
LIST_SALES_UPDATE_CONTRACT = "6"
LIST_SALES_CREATE_EVENT = "7"
# Dossier et Nom fichier

DATA_FOLDER = "data"
REPORTS_FOLDER = "reports"
FILE_NAME = "players.json"
FILE_NAME2 = "tournament.json"
TEMPLATES = "templates/template.html"
TEMPLATES_LIST_TOURNAMENT = "templates/template_list_tournament.html"
TEMPLATES_DETAILS = "templates/template_details_tournament.html"
TEMPLATES_DATE = "templates/template_date_tournament.html"

# Tournament Menu

TOURNAMENT_MENU_NOUVEAU = "1"
TOURNAMENT_MENU_AFFICHER = "2"
TOURNAMENT_MENU_LANCER = "3"
TOURNAMENT_MENU_REPRENDRE = "4"
TOURNAMENT_MENU_QUIT = "0"

# Etat tournoi

TO_LAUNCH = "TO LAUNCH"
IN_PROGRESS = "IN PROGRESS"
FINISH = "FINISH"

# Report Menu

REPORT_MENU_LISTE_JOUEUR_ALPHA = "1"
REPORT_MENU_LISTE_TOURNOI = "2"
REPORT_MENU_LISTE_DATE_TOURNOI = "3"
REPORT_MENU_LISTE_JOUEUR_TOURNOI = "4"
REPORT_MENU_LISTE_ROUND_MATCH_TOURNOI = "5"
REPORT_MENU_QUIT = "0"

# ERROR

ERR_USER_NOT_FOUND = "USER not found"
ERR_USER_NO_ROLE = (
    "This USER has no role, he cannot interact with the application"
)
